openapi: 3.0.3
info:
  title: Deep Narrative Analysis RESTful APIs v1.0.1
  description: |-
    Defines the interface for ingesting, retrieving, editing and deleting 
    narratives using the Deep Narrative Analysis (DNA) infrastructure.
    
    Some useful links:
    - [GitHub DNA repository](https://github.com/ontoinsights/deep_narrative_analysis)
    - [DNA blog](https://hearing-all-voices.blogspot.com/)
  contact:
    email: andrea@ontoinsights.com
  license:
    name: Creative Commons Attribution 4.0 International Public License
    url: https://creativecommons.org/licenses/by/4.0/legalcode
  version: '1.0'
paths:
  /dna/v1/repositories:
    get:
      summary: >-
        Get a list of all repositories
      description: >-
        Return the names and creation dates of all the narrative repositories
      operationId: getRepositories
      responses:
        '200':
          description: Successful operation (may be empty)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepositoryList' 
        '500':
          description: Internal processing error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'  
    post:
      summary: >-
        Create a new repository
      description: >-
        Create a new narrative repository with the specified name
      parameters:
        - $ref: '#/components/parameters/repository'
      operationId: createRepository
      responses:
        '201':
          description: Repository created
          content:
            application/json:
              schema:
                type: object
                properties:
                  repository:
                    type: string
                    example: dna
                  created:
                    type: string
                    format: date-time
                    example: 2022-07-14T17:32:28Z
        '400':
          description: Repository creation - Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Query parameter ?repository not specified
        '409':
          description: Repository already exists
        '500':
          description: Internal processing error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'  
    delete:
      summary: Delete a repository
      description: >-
        Delete the narrative repository of the specified name
      parameters:
        - $ref: '#/components/parameters/repository'
      operationId: deleteRepository
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  repository:
                    type: string
                    example: dna
        '404':
          description: Repository not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: Internal processing error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'  
  /dna/v1/narratives:
    get:
      summary: >-
        Get a list of all narratives and their meta-data in the 
        specified repository
      description: >-
        Return the meta-data for all narratives in the specified repository
      parameters:
        - $ref: '#/components/parameters/repository'
      operationId: getList
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NarrativeList' 
        '404':
          description: Repository not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'  
        '500':
          description: Internal processing error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'  
    post:
      summary: Ingest a narrative to the specified repository
      description: >-
        Process a narrative based on details in the request body 
        and ingest it to the specified repository
      parameters:
        - $ref: '#/components/parameters/repository'
      operationId: ingest
      requestBody:
        description: Ingest narrative
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputNarrative'  
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NarrativeMeta'
        '400':
          description: Missing or invalid content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'  
        '404':
          description: Repository not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'  
        '409':
          description: >-
            Duplicate title; A narrative with the specified title is
            already present in the repository
        '500':
          description: Internal processing error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'  
    delete:
      summary: Delete a narrative
      description: >-
        Delete the specified narrative in the repository
      parameters:
        - $ref: '#/components/parameters/repository'
        - $ref: '#/components/parameters/narrativeId'
      operationId: deleteNarrative
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  repository:
                    type: string
                    example: dna
                  narrativeId:
                    type: string
                    example: 73cf1b89
        '400':
          description: Missing or invalid content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'  
        '404':
          description: Repository or narrative ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'  
        '500':
          description: Internal processing error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'  
  /dna/v1/narratives/graphs:
    get:
      summary: Get a narrative's knowledge graph
      description: >-
        Get the knowledge graph for the narrative with the specified id
        in the repository
      operationId: getGraph
      parameters:
        - $ref: '#/components/parameters/repository'
        - $ref: '#/components/parameters/narrativeId'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KnowledgeGraph'  
        '400':
          description: Missing or invalid content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'  
        '404':
          description: Repository or narrative ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'  
        '500':
          description: Internal processing error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'  
    put:
      summary: Update a narrative's knowledge graph
      description: >-
        Update the knowledge graph for the specific narrative 
        in the repository
      operationId: updateGraph
      parameters:
        - $ref: '#/components/parameters/repository'
        - $ref: '#/components/parameters/narrativeId'
      requestBody:
        description: Knowledge graph details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KnowledgeGraph'  
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NarrativeMeta'  
        '400':
          description: Update knowledge graph - Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'  
        '404':
          description: Repository or narrative ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'  
        '500':
          description: Internal processing error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'  
components:
  parameters:
    repository:
      name: repository
      in: query
      description: >-
        Name of the repository holding the narratives
      required: true
      schema:
        type: string
    narrativeId:
      name: narrativeId
      in: query
      description: UUID for a narrative in the repository
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    BadRequest:
      type: array
      items:
        type: array
        items:
          type: object
          properties:
            entity:
              type: string
              enum: [ GRAPH_ERROR, MISSING_CONTENT ]
              example: MISSING_CONTENT
            inputValue:
              type: string
              example: string or null
            errorDetail:
              type: string
              example: Missing narrative title
    InputNarrative:
      type: object
      properties:
        title:
          type: string
          example: A Narrative Title
        narrative:
          type: string
          example: This is the text of the narrative.
    InternalError:
      type: object
      properties:
        error:
          type: string
          example: Error details
    KnowledgeGraph:
      type: object
      properties:
        title:
          type: string
          example: A New Title
        numberOfTriples:
          type: integer
          format: int64
          example: 500
        triples:
          type: array
          items:
            type: object
            properties:
              subject:
                type: string
                example: dna:Event1
              predicate:
                type: string
                example: rdfs:label
              objectType:
                type: string
                enum: [ DATA, OBJECT ]
                example: DATA
              object:
                type: string
                example: Event1 label
    NarrativeList:
      type: object
      properties:
        repository:
          type: string
          example: dna
        narratives:
          type: array
          items:
            type: object
            properties:
              narrativeId:
                type: string
                example: 73cf1b89
              title:
                type: string
                example: A Narrative Title
              numberOfTriples:
                type: integer
                format: int64
                example: 500
    NarrativeMeta:
      type: object
      properties:
        repository:
          type: string
          example: dna
        narrativeId:
          type: string
          example: 73cf1b89
        title:
          type: string
          example: A Narrative Title
        numberOfTriples:
          type: integer
          format: int64
          example: 500
    NotFound:
      type: array
      items:
        type: object
        properties:
          missingEntity:
            type: string
            enum: [ REP, NARR_ID ]
            example: REP
          inputString:
            type: string
            example: foo
    RepositoryList:
      type: array
      items:
        $ref: '#/components/schemas/RepositoryMeta'  
    RepositoryMeta:
      type: object
      properties:
        repositoryName:
          type: string
          example: narratives1
        creationDate:
          type: string
          format: date-time
          example: 2022-07-21T17:32:28Z
